### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by ccmoralesj** [neist/graphql-combine#1]
Hey there, I really like this library and I was wondering. Are you going to create a `d.ts` file for TypeScript support? :smile:

**Comment by neist** [comment]
Hey! Sorry for the late reply! Glad you like the library 👍 I'm not personally using typescript, so I have no plans to add it myself. But I will be happy to accept a pull request - the module is small and simple, so it should be easy to add 😄

**Comment by neist** [comment]
I'm closing this issue. Feel free to re-open if you have any further inputs 😊
